---
name: Sync RSS
on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/1 * * * *'

jobs:
  sync:
    name: Setup environment
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
      - run: |
          echo ${{ env.LIBSYN_RSS_URL }}
          npx @k8adev/feeder --rss ${{ env.LIBSYN_RSS_URL }} -f "feed"
          npx @k8adev/feeder --rss ${{ env.LIBSYN_RSS_URL }} -f "feed" --json
      - uses: actions/upload-artifact@v2
        with:
          name: feed
          path: public/feed.json
      - uses: actions/upload-artifact@v2
        with:
          name: feed
          path: public/feed.xml
  commit:
    runs-on: ubuntu-latest
    needs: sync
    permissions:
      contents: write
    steps:
      - name: Setup environment
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v2
        with:
          name: feed
          path: public

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: auto update RSS"
          commit_options: --no-verify
          file_pattern: public/feed.*
          repository: ${{ github.repository }}
          branch: ${{ github.ref }}
